version: "3.9"

services:

  trainer:
    build: .
    container_name: vad-trainer
    command: sh -c "while true; do python mlflow_pipeline/train_branches.py; echo 'Retraining in 60s...'; sleep 60; done"
    volumes:
      - .:/app

  api:
    build: .
    container_name: vad-api
    depends_on:
      - trainer
    command: uvicorn api.main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    volumes:
      - .:/app